server:
    port: 8081
spring:
    liquibase:
        change-log: classpath:liquibase/changelog_v1.yaml
        enabled: true
    jpa:
        open-in-view: true
        show-sql: false
        hibernate:
           ddl-auto: validate
           format_sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        url: jdbc:postgresql://localhost:5432/deal_db
        username: user
        password: pass
    cloud:
        openfeign:
            client:
                config:
                    conveyor:
                        url: http://localhost:8080/