server:
    port: 8081
spring:
    jpa:
        open-in-view: true
        show-sql: false
        hibernate:
           ddl-auto: update
           format_sql: true
    datasource:
        url: jdbc:postgresql://localhost:5432/deal_db
        username: user
        password: pass