openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8082
  description: Generated server url
paths:
  /application:
    post:
      tags:
      - application-controller
      summary: Calculation of possible loan offers
      description: Returns four LoanOfferDTO or message with the reason for rejection
        of the application
      operationId: createLoanOffers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanApplicationRequestDTO'
        required: true
      responses:
        "409":
          description: Client has approved application and application cannot be changed
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoanOfferDTO'
        "400":
          description: LoanApplicationRequestDTO is not valid
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoanOfferDTO'
        "500":
          description: Deal server unavailable or internal server error occured
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoanOfferDTO'
        "200":
          description: "CreditDTO successfully created or the application was rejected,\
            \ but LoanApplicationRequestDTO was valid"
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoanOfferDTO'
  /application/offer:
    post:
      tags:
      - application-controller
      summary: Select loan offer
      description: Receives offer selected by user and save it to database
      operationId: saveLoanOffer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanOfferDTO'
        required: true
      responses:
        "400":
          description: LoanOfferDTO is not valid
        "404":
          description: Application for LoanOfferDTO not found
        "409":
          description: The application has already been approved and cannot be changed
        "200":
          description: Loan offer was successfully saved
components:
  schemas:
    LoanApplicationRequestDTO:
      required:
      - amount
      - birthdate
      - email
      - firstName
      - lastName
      - middleName
      - passportNumber
      - passportSeries
      - term
      type: object
      properties:
        amount:
          type: number
          description: Requested loan amount
          example: 100000
        term:
          type: integer
          description: Term of loan in months
          format: int32
          example: 10
        firstName:
          maxLength: 30
          minLength: 2
          pattern: "[A-Z][a-zA-Z]*"
          type: string
          description: User's firstname
          example: Anna
        lastName:
          maxLength: 30
          minLength: 2
          pattern: "[A-Z][a-zA-Z]*"
          type: string
          description: User's lastname
          example: Petrova
        middleName:
          maxLength: 30
          minLength: 2
          pattern: "[A-Z][a-zA-Z]*"
          type: string
          description: User's middle name
          example: Sergeevna
        email:
          pattern: "[A-Za-z0-9_-]+@[A-Za-z0-9_-]+\\.[A-Za-z.]+"
          type: string
          description: User's email
          example: example@mail.ru
        birthdate:
          type: string
          description: User's birthdate. Should be before today
          format: date
          example: 1990-01-01
        passportSeries:
          pattern: "\\d{4}"
          type: string
          description: User's passport series
          example: "1111"
        passportNumber:
          pattern: "\\d{6}"
          type: string
          description: User's passport number
          example: "222222"
    LoanOfferDTO:
      required:
      - applicationId
      - isInsuranceEnabled
      - isSalaryClient
      - monthlyPayment
      - rate
      - requestedAmount
      - term
      - totalAmount
      type: object
      properties:
        applicationId:
          minimum: 0
          type: integer
          description: ID of user's application
          format: int64
          example: 1
        requestedAmount:
          minimum: 0
          type: number
          description: Requested amount
          example: 100000
        totalAmount:
          minimum: 0
          type: number
          description: Total amount with insurance (if enabled)
          example: 130000
        term:
          minimum: 0
          type: integer
          description: Term of loan in months
          format: int32
          example: 10
        monthlyPayment:
          minimum: 0
          type: number
          description: Loan monthly payment
          example: 13300
        rate:
          minimum: 0
          type: number
          description: Interest rate per annum
          example: 5
        isInsuranceEnabled:
          type: boolean
          description: Is insurance enabled
          example: true
        isSalaryClient:
          type: boolean
          description: Is the user salary client
          example: true
