name: Build and Test Conveyor Application

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Conveyor
        working-directory: Conveyor
        run: mvn clean verify

      - name: Build Dossier
        working-directory: Dossier
        run: mvn clean verify

      - name: Build Deal
        working-directory: Deal
        run: mvn clean verify

      - name: Build Application
        working-directory: Application
        run: mvn clean verify

      - name: Build Application
        working-directory: Gateway
        run: mvn clean verify

      - name: Upload coverage reports to Codecov for Conveyor
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./Conveyor/target/site/jacoco/jacoco.xml
          flags: unit_tests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true

      - name: Upload coverage reports to Codecov for Dossier
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./Dossier/target/site/jacoco/jacoco.xml
          flags: unit_tests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true

      - name: Upload coverage reports to Codecov for Deal
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./Deal/target/site/jacoco/jacoco.xml
          flags: unit_tests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true

      - name: Upload coverage reports to Codecov for Application
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./Application/target/site/jacoco/jacoco.xml
          flags: unit_tests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
